### ISSUE TITLE
When using `urxvtd`, it sometimes stops responding to HUP

### ISSUE THREAD

**Issue by machinedgod** [regnarg/urxvt-config-reload#19]
I'm sending the signal straight to `urxvtd`, and it changes all `urxvtc`s normally, but -I don't know what is the trigger- as title says, at one point it just stops responding to the signal.
Newly spawned clients are coloured appropriately so I'm pretty sure the issue is in the plugin.

**Comment by qualiaa** [comment]
@machinedgod Can you try the #18 PR? I haven't tested with urxvtd but this sounds like similar behaviour observed with tabs.

**Comment by machinedgod** [comment]
Hey, thanks for responding so quickly!
I modded my distro's package to pick up new sources, working as a charm.
Thank you!
