### ISSUE TITLE
Global symbol "$TERM" requires explicit package name (did you forget to declare "my $TERM"?) at .urxvt/ext/config-reload

### ISSUE THREAD

**Issue by GeekyPeas** [regnarg/urxvt-config-reload#23]
Something is broken and I am not sure what. Now if I run `kill -1 $(pgrep urxvt)` nothing happens. So I tried to run the command directly through:

    perl .urxvt/ext/config-reload

And I got this error message:

    Global symbol "$TERM" requires explicit package name (did you forget to declare "my $TERM"?) at .urxvt/ext/config-reload line 82.
    Global symbol "$TERM" requires explicit package name (did you forget to declare "my $TERM"?) at .urxvt/ext/config-reload line 83.
    Global symbol "$TERM" requires explicit package name (did you forget to declare "my $TERM"?) at .urxvt/ext/config-reload line 90.
    Execution of .urxvt/ext/config-reload aborted due to compilation errors.

However if I `echo $TERM` I get `rxvt-unicode`.

p.s.: Sorry I am not a `perl` guy.

**Comment by GeekyPeas** [comment]
I have replaced `$TERM` throughout with `$ENV{TERM}`. It lets 

    perl .urxvt/ext/config-reload

to execute without any errors. However still `kill -1 $(pgrep urxvt)` does nothing.

**Comment by regnarg** [comment]
> So I tried to run the command directly through:

This is an urxvt plugin, i.e., a piece of code that runs within the urxvt process. It makes no sense whatsoever to run it directly as a script.

**Comment by regnarg** [comment]
And `$TERM` is an urxvt global variable holding the internal terminal object, not the `TERM` environment variable.

**Comment by GeekyPeas** [comment]
I am not sure what exactly fixed it either - but it works now! 

> And `$TERM` is an urxvt global variable holding the internal terminal object, not the `TERM` environment variable.

So I reverted to using `$TERM` instead of `$ENV{TERM}`.

I did some other changes but I didn't track them all. It is working now though.
