### ISSUE TITLE
Add support for borderColor

### ISSUE THREAD

**Issue by andrew-ws** [regnarg/urxvt-config-reload#8]
This doesn't reload borderColor, the attribute for the color of the internalBorder. Should just be a couple lines, I'd submit a pull request but I don't know much perl.

**Comment by qualiaa** [comment]
The support for this is already there, but the script looks for `border` rather than `borderColor`. I'll submit a pull-request regularising the key names.

**Comment by regnarg** [comment]
Resolved by #14
